name: develop
on:
  pull_request:
    branches: test

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi
      - name: Context
        run: echo "context ${{ toJson(github) }}"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Update minor version
        run: yarn minor_update

      - name: Commit new version
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions 
          message: "Updated minor version"
          add: app.json
          
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name: Get app version
        id: app_version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'app.json'
          prop_path: 'expo.version'

      - name: Get runtime version
        id: runtime_version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'app.json'
          prop_path: 'expo.runtimeVersion'

      - uses: mshick/add-pr-comment@v2
        with:
          message: |
            **Hello**
            🌏
            app v.${{steps.app_version.outputs.propStr}}
            runtime v.${{steps.runtime_version.outputs.prop}}

      - uses: tzkhan/pr-update-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          title-template: '[App v${{steps.app_version.outputs.propStr}}] '

      - name: Publish update
        run: eas update --channel uat --message ${{steps.app_version.outputs.propStr}}

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Create preview
        uses: expo/expo-github-action/preview@v8
        with:
          command: eas update --channel development --message ${{ github.head_ref }}
