name: development
on:
  pull_request:
    branches: develop
    types: [opened, synchronize, reopened]

run-name: Update Development using ${{ github.head_ref }}

jobs:
  setup:
    runs-on: ubuntu-latest

    outputs:
      is_maintenance: ${{ steps.is_maintenance.outputs.result }}

    steps:
      - name: Check if maintenance
        id: is_maintenance
        run: |
          if [[ "${{ github.head_ref }}" =~ ^(fix/|change/) ]]; then
            echo "result=false" >> "$GITHUB_OUTPUT"
          else
            echo "result=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Summary
        run: |
          echo "IsMaintenance: ${{ steps.is_maintenance.outputs.result }}"

  update:
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ needs.setup.outputs.is_maintenance == 'false'}}

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Create preview
        uses: expo/expo-github-action/preview@v8
        with:
          command: eas update --channel development --message ${{ github.head_ref }}

      - name: Summary
        run: |
          echo "Channel development updated
          ${{ github.head_ref }}
          " >> $GITHUB_STEP_SUMMARY

  maintenance:
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ needs.setup.outputs.is_maintenance == 'true' }}

    steps:
      - name: Summary
        run: echo "Some maintenance work" >> $GITHUB_STEP_SUMMARY
