name: production
on:
  push:
    branches: master

jobs:
  update:
    name: EAS production Update
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Update major version
        run: yarn major_update

      - name: Commit new version
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Updated major version"
          add: app.json

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Get app version
        id: app_version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'app.json'
          prop_path: 'expo.version'

      - name: Get runtime version
        id: runtime_version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'app.json'
          prop_path: 'expo.runtimeVersion'

      - uses: mshick/add-pr-comment@v2
        with:
          message: |
            Channel production
            app ${{steps.app_version.outputs.prop}}
            runtime ${{steps.runtime_version.outputs.prop}}

      - name: Publish update
        run: eas update --channel production --message ${{steps.app_version.outputs.propStr}}