name: uat
on:
  push:
    branches: develop

jobs:
  update:
    name: EAS uat Update
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    if: startsWith(github.head_ref, 'fix/') || startsWith(github.head_ref, 'change/')
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Minor version update
        working-directory: ${{ github.workspace }}
        id: version_update
        run: |
          npm install commander > /dev/null
          echo "VERSION_SUMMARY=$(node ./.github/updateVersion.js -f app.config.js --field version)" >> "$GITHUB_OUTPUT"
        continue-on-error: false

      - name: Commit new version
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Updated minor version: ${{ steps.version_update.outputs.VERSION_SUMMARY }}"
          add: app.config.js
        continue-on-error: false

      - name: Get runtime version
        working-directory: ${{ github.workspace }}
        id: runtime_version
        run: echo "RUNTIME_VERSION=$(node ./.github/getVersion.js -f app.config.js)" >> "$GITHUB_OUTPUT"

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - uses: mshick/add-pr-comment@v2
        with:
          message: |
            Channel uat updated
            App Version: ${{ steps.version_update.outputs.VERSION_SUMMARY }}
            Runtime Version: ${{steps.runtime_version.outputs.RUNTIME_VERSION}}

      - name: Publish update
        run: eas update --channel uat --message ${{steps.app_version.outputs.propStr}}
        continue-on-error: false

      - name: Summary
        run: echo "Successfully updated UAT with version ${{ steps.version_update.outputs.VERSION_SUMMARY }}" >> $GITHUB_STEP_SUMMARY

  maintenance:
    runs-on: ubuntu-latest
    steps:
      - name: Summary
        run: echo "Just environment/maintenance change do not need any update" >> $GITHUB_STEP_SUMMARY